# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_and_release:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
  
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Restore Packages
      run: nuget restore glc_cs.sln

    - name: Build solution
      run: msbuild glc_cs.sln -t:rebuild -property:Configuration=Release
      
    - name: Zip output
      run: |
        cd .\glc_cs\bin\Release\
        powershell compress-archive *.* Release
        
    - name: Upload build as artifact
      uses: actions/upload-artifact@v2
      with:
        name: glc_release
        path: ./Release.zip
    
