# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_and_release:

    runs-on: windows-2019
    strategy:
      matrix:
        goos: [windows]
        goarch: ["386", amd64, arm64]
        exclude:
          - goarch: "386"
            goos: windows

    steps:
    - uses: actions/checkout@v3

    - uses: wangyoucao577/go-release-action@v1
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          compress_assets: OFF
          md5sum: FALSE

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
  
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Restore Packages
      run: nuget restore glc_cs.sln

    - name: Build solution
      run: msbuild glc_cs.sln -t:rebuild -property:Configuration=Release
      
